// Compiles the JSX inside index.html to app.build.js and stamps the page with the hash of
// the source it compiled, so the browser can tell whether the artefact is still current.
//
// Uses the same @babel/standalone version and preset the browser fallback would use, so the
// compiled output is exactly what the page produced at runtime before — just done once, here,
// instead of on every visitor's device.
//
//   npm run build
import fs from 'fs';
import crypto from 'crypto';
import path from 'path';
import { fileURLToPath } from 'url';
import * as Babel from '@babel/standalone';

const root = path.dirname(fileURLToPath(import.meta.url));
const HTML = path.join(root, 'index.html');
const OUT = path.join(root, 'app.build.js');

const html = fs.readFileSync(HTML, 'utf8');

// Match the app script and capture its contents exactly as the DOM would expose them
// via textContent — that is what the runtime check hashes.
const re = /(<script type="text\/babel"[^>]*id="app-src"[^>]*>)([\s\S]*?)(<\/script>)/;
const m = html.match(re);
if (!m) {
  console.error('build: could not find <script type="text/babel" id="app-src"> in index.html');
  process.exit(1);
}
const [, openTag, source] = m;

const sha256 = s => crypto.createHash('sha256').update(s, 'utf8').digest('hex');
const hash = sha256(source);

let code;
try {
  ({ code } = Babel.transform(source, { presets: ['react'] }));
} catch (e) {
  console.error('build: JSX failed to compile —', e.message);
  process.exit(1);
}

const banner = `/* Generated by build.mjs from index.html — do not edit.\n` +
               `   Source SHA-256: ${hash}\n` +
               `   Edit the JSX in index.html and re-run: npm run build */\n`;
fs.writeFileSync(OUT, banner + code);

const stamped = html.replace(re, (_all, open, src, close) =>
  open.replace(/data-build-hash="[^"]*"/, `data-build-hash="${hash}"`) + src + close);

if (stamped === html && !openTag.includes(hash)) {
  console.error('build: failed to stamp data-build-hash into index.html');
  process.exit(1);
}
fs.writeFileSync(HTML, stamped);

const kb = n => (n / 1024).toFixed(0) + ' KB';
console.log(`build: ${kb(source.length)} of JSX -> ${kb(code.length)} of JS`);
console.log(`build: source hash ${hash.slice(0, 12)}… stamped into index.html`);
console.log('build: browsers now skip the 2.3MB Babel download and the in-page compile.');
